### ISSUE TITLE
Using CurrentSite

### ISSUE THREAD

**Issue by dnwhte** [kgiszewski/G42.UmbracoGrease#5]
Hey @kgiszewski 

How would I go about using **CurrentSite** in instead of **NodeHelper.Instance.CurrentSite**?

**Comment by kgiszewski** [comment]
NodeHelper takes an inventory of all the domains at startup and their associated root nodes.

`CurrentSite` is just a lookup of that inventory.

https://github.com/kgiszewski/G42.UmbracoGrease/blob/6a853a52569a8de6fa36b4578db62c57ed74cc61/src/G42.UmbracoGrease/G42NodeHelper/NodeHelper.cs#L62-L65

It is also an instance member of NodeHelper (which is a singleton) so you won't be able to call it by itself.

**Comment by dnwhte** [comment]
Thanks. Is it safe to alias it in another helper? Ex

```cs
    public class ExampleHelper
    {
        public static Site Site {
            get {
                return SiteHelper.Instance.CurrentSite;
            }
        }
    }
```

**Comment by kgiszewski** [comment]
Should be 🤔
